disabled_rules:
  - trailing_whitespace
  - colon
  - comma

opt_in_rules:
  - empty_count

included:
  - "Tracker for YandexSchool/"

excluded:
  - Pods


line_length:
  warning: 160
  error: 180
  ignores_comments: true
  ignores_interpolated_strings: true

type_name:
  min_length: 1
  max_length: 40
  excluded:
    - id
    - i
